apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    name: web-pod
    type: web-app
spec:
  containers:
    - name: web-app
      image: sanskardevops/go-k8s-ecs-restapi:latest
      env:
        - name: POSTGRES_USER
          value: "sanskarrestapi"
        - name: POSTGRES_PASSWORD
          value: "sanskarrestapi"
        - name: POSTGRES_DB
          value: "sanskarrestapi"
      ports: 
        - containerPort: 3000
      
     