apiVersion: v1
kind: Service

metadata:
  name: web-service 
  labels:
    name: web-service

spec:
  type: NodePort
  selector:
    name: web-pod
    type: web-app
  ports: 
  - port: 3000
    targetPort: 3000
    nodePort: 30002
